<!DOCTYPE html>
<html>
<head>
    <title>GruziVizi</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            padding: 1% 5% 2% 5%;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>GruziVizi</h1>
    <hr>
    <h2>Панель администратора</h2><br>
    <a href="/admin/usersPanel" class="btn btn-primary">Управление пользователями</a> <br><br>
    <a href="/admin/ordersPanel" class="btn btn-primary">Управление заказами</a> <br><br>
    <a href="/admin/vehiclesPanel" class="btn btn-primary">Управление транспортом</a> <br><br>
</div>

<!-- Add Bootstrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
